config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # ゲストログイン
  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 会員側
  scope module: :public do
    root to: "homes#top"
    get "home/about" => "homes#about", as: 'about'
    get 'searches/search'
    resources :items, only: [:index, :show]
    resources :posts, only: [:new, :index, :show, :update, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      get   "/comfirm"    => :comfirm
      patch "/withdraw"   => :withdraw
    end
  end


  # 管理者用
  namespace :admin do
    root to: "homes#top"
    resources :items, except: [:destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!
  
  def search
    @model = params[:model]
    @keyword = params[:keyword]
    
    # 選択したモデルに応じて検索を実行
    if @model == "user"
      @results = User.search(@keyword)
    else
      @results = Item.search(@keyword)
    end
  end
end

app/views/admin/searches/_form.html.erb
<div class='container mb-2'>
  <div class='row'>
  	<div class='mx-auto'>
  	  <!--ログアウト時に検索画面が出ていないようにできています。-->
  	  <% if user_signed_in? %>
        <%= form_with url: searches_search_path, method: "get", local: true do |f| %>
          <%= f.text_field :keyword %>
          <%= f.select :model, options_for_select({ 'User' => 'user', 'Item' => 'item' }) %>
          <%= submit_tag "検索" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/searches/search.html.erb
<% if @model == 'item' %>
    <h3>Users search for "<%= @keyword %>"</h3>
  <%= render 'admin/items/index', items: @results %>
<% elsif @model == 'user' %>
    <h3>Posts search for "<%= @keyword %>"</h3>
  <%= render 'admin/posts/index', posts: @results %>
<% end %>