config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # ゲストログイン
  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 会員側
  scope module: :public do
    root to: "homes#top"
    get "home/about" => "homes#about", as: 'about'
    get 'searches/search'
    resources :items, only: [:index, :show]
    resources :posts, only: [:new, :index, :show, :update, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      get   "/comfirm"    => :comfirm
      patch "/withdraw"   => :withdraw
    end
  end


  # 管理者用
  namespace :admin do
    root to: "homes#top"
    resources :items, except: [:destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :comments
  has_many :posts
  has_one_attached :profile_image
  
  validates :name, presence: true
  validates :email, presence: true
  
  def self.search(keyword)
    Item.where('name LIKE ?','%'+ keyword + '%')
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    if params[:search].present?
      search_users = User.select { |user| user.name.include?(params[:search]) }
      @users = Kaminari.paginate_array(search_users).page(params[:page])
      @heading = "「#{params[:search]}」の検索結果"
    else
      @users = User.page(params[:page]).per(8)
      @heading = "会員一覧"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :info, :profile_image, :color, :is_active)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center ">
    <h2 class='text-new'><%= @user.name %>さんの会員情報編集</h2>
  </div>
  <div class="row">
    <div class="col">
      <%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>
        <%= render "public/shared/error_messages", resource: @user %>
        <table class='table'>
          <tr>
            <th><%= f.label :name, "ニックネーム" %></th>
            <td><%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "sample" %></td>
          </tr>
          <tr>
            <th><%= f.label :email, "メールアドレス" %></th>
            <td><%= f.email_field :email, autocomplete: "email", placeholder: "sample@example.com" %></td>
          </tr>
          <tr>
            <th><%= f.label :info, "自己紹介" %></th>
            <td><%= f.text_field :infoo, placeholder: "よろしくお願いします" %></td>
          </tr>
          <tr>
            <th><%= f.label :color, "好きな色" %></th>
            <td><%= f.color_field :color %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <%= f.radio_button :is_active, true, id: "active_true" %>
              <%= f.label :is_active, "有効", for: "active_true" %>
              <%= f.radio_button :is_active, false, id: "active_false" %>
              <%= f.label :is_active, "退会", for: "active_false" %>
            </td>
          </tr>
        </table>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-6 text-center"> 
              <%= f.submit "変更を保存", class: "btn btn-md custom-button" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row justify-content-center ">
    <h2 class='text-new'>会員一覧</h2>
  </div>
  <div class="row">
    <div class="col">
      <table class="table">
        <thead class="table-dark">
          <tr align="center">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr align="center">
            <td><%= user.id %></td>
            <td><%= link_to user.name, admin_user_path(user) %></td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_active %>
                <p class="text-success"><strong>有効</strong></p>
              <% elsif %>
                <p class="text-muted"><strong>退会</strong></p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center">
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row justify-content-center ">
    <h2 class='text-new'><%= @user.name %>さんの会員詳細</h2>
  </div>
  <div class="row">
    <table class="table">
      <tr>
        <th>会員ID</th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>自己紹介</th>
        <td><%= @user.info %></td>
      </tr>
      <tr>
        <th>好きな色</th>
        <td><div class="color_circle m-1" style="background-color: <%= @user.color %>;"></div></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <% if @user.is_active %>
            <p class="text-success"><strong>有効</strong></p>
          <% elsif %>
            <p class="text-muted"><strong>退会</strong></p>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 text-center"> 
        <%= link_to "編集する", edit_admin_user_path, class: "btn btn-md custom-button" %>
      </div>
    </div>
  </div>
</div>