config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /users/sign_in...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # ゲストログイン
  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  # URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 会員側
  scope module: :public do
    root to: "homes#top"
    get "home/about" => "homes#about", as: 'about'
    get 'searches/search'
    resources :items, only: [:index, :show]
    resources :posts, only: [:new, :index, :show, :update, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      get   "/comfirm"    => :comfirm
      patch "/withdraw"   => :withdraw
    end
  end


  # 管理者用
  namespace :admin do
    root to: "homes#top"
    resources :items, except: [:destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true, length: {maximum: 150}
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :posts
  
  validates :name, presence: true
  validates :price, presence: true
  validates :capacity, presence: true
  
  # 投稿画像がなかったときno_imageを表示する
  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
  
  def self.search(keyword)
    Item.where('name LIKE ?','%'+ keyword + '%')
  end
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  belongs_to :item
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :star,presence:true
  validates :introduction,presence:true,length:{maximum:400}
  
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}

  def self.tag_search(keyword)
    Post.joins(:tags).where('tags.tag_name LIKE ?','%'+ keyword + '%')
  end

  def save_tags(savepost_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - savepost_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = savepost_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tag_name:old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(tag_name: new_name)
      self.tags << post_tag
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  
  def self.search(keyword)
    Tag.where('name LIKE ?','%'+ keyword + '%')
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  
  validates :tag_name, presence:true, length:{maximum:50}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :comments
  has_many :posts
  has_one_attached :profile_image
  
  validates :name, presence: true
  validates :email, presence: true
  
  def self.search(keyword)
    Item.where('name LIKE ?','%'+ keyword + '%')
  end
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to edit_admin_item_path(@item.id)
    else
      render :new
    end
  end 
  
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :capacity, :is_active)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
  end

  def show
  end

  def destroy
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!
  
  def search
    @model = params[:model]
    @keyword = params[:keyword]
    
    # 選択したモデルに応じて検索を実行
    if @model == "user"
      @results = User.search(@keyword)
    else
      @results = Item.search(@keyword)
    end
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    if params[:search].present?
      search_users = User.select { |user| user.name.include?(params[:search]) }
      @users = Kaminari.paginate_array(search_users).page(params[:page])
      @heading = "「#{params[:search]}」の検索結果"
    else
      @users = User.page(params[:page]).per(8)
      @heading = "会員一覧"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :info, :profile_image, :color, :is_active)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when User
      root_path
    else
      root_path
    end
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto text-center">
      <%= link_to admin_session_path, class: "inline" do %>
        <span>&copy;</span> 
      <% end %>
      <p style="display: inline-block;">Copyright 2024 Fragrance Palette. All rights reserved.</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/"><span><h4>Fragrance Palette</h4></span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% if admin_signed_in? %>
      <!--管理者がログインしている場合-->
        <li>
          <%= link_to new_admin_item_path, class: 'nav-link' do %>
            <i class="fa-solid fa-check"></i> new
          <% end %>
        </li>
        <li>
          <%=  link_to admin_users_path,class: 'nav-link' do %>
            <i class="fas fa-users"></i> users
          <% end %>
        </li>
        <li>
          <%= link_to admin_items_path, class: 'nav-link' do %>
            <i class="fa-solid fa-spray-can-sparkles"></i> fragrance
          <% end %>
        </li>
        <li>
          <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link' do %>
            <i class="fas fa-sign-out-alt"></i> log out
          <% end %>
        </li>
      <% elsif user_signed_in? %>
      <!--顧客がログインしている場合-->
        <li>
          <%= render 'public/searches/form' %>
        </li>
        <li>
          <%= link_to user_path(current_user.id), class: 'nav-link' do %>
            <i class="fa-solid fa-user"></i> mypage
          <% end %>
        </li>
        <li>
          <%= link_to items_path, class: 'nav-link' do %>
            <i class="fa-solid fa-spray-can-sparkles"></i> fragrance
          <% end %>
        </li>
        <li>
          <%= link_to posts_path, class: 'nav-link' do %>
            <i class="fa-solid fa-comment"></i> post
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
            <i class="fas fa-sign-out-alt"></i> log out
          <% end %>
        </li>
      <% else %>
      <!--どちらもログインしていない場合-->
        <li>
          <%= render 'public/searches/form' %>
        </li>
        <li>
          <%= link_to items_path,class: 'nav-link' do %>
            <i class="fa-solid fa-spray-can-sparkles"></i> fragrance
          <% end %>
        </li>
        <li>
          <%= link_to posts_path, class: 'nav-link' do %>
            <i class="fa-solid fa-comment"></i> post
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path ,class: 'nav-link' do %>
            <i class="fas fa-sign-in-alt"></i> login
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColorF</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cbc377acd8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main class="main">
      <%= yield %>
    </main>
    <footer class="mt-3 bg-light">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>